"""this module contains a class that handles downoading, processing and saving data"""
import sqlite3
import datetime

class DataHandler:
    """this class handles downoading, processing and saving data"""

    def __init__(self, database_path : str) -> None:
        # connecting to database 
        self.connection = sqlite3.connect(database_path)

    def download_data(self) -> list:
        """
        this method downloads data from premium_payments table
            :returns
            data : pythonlist with a tuple representing eah row in the table
        """
        # running sql select statement over premium_payments ordered by member_id and date_start
        iterable = self.connection.execute("""
            SELECT member_id, date(date_start) as date_start, date(date_end) as date_end, type 
            FROM premium_payments
            ORDER BY member_id, date_start
        """)
        # getting all data returned by the sql statement
        data = list(iterable)

        return data

    def process_data(self, data) -> list:
        """
        this method takes data fetched from premium_payments table and 
        ordered by  member_id, date_start and creates a table that 
        contains a row per subscription to premium with 
        the member_id, the type of the souscription (1 to 3)
        the starting date and the ending date.
            :params
            data : list of tuples generated by download_data
            :returns
            processed_data : list of tuples of  the new table like describes before
        """
        # initializing variables
        member_id = date_start = date_end = type = None
        processed_data = []
        for row in data:
            # for each row in table
            if member_id is None:
                # case of first row
                member_id, date_start, date_end, type = row

            elif member_id != row[0]:
                # case of new member_id

                # inserting old row and creating new one
                processed_data.append((member_id, date_start, date_end, type))
                member_id, date_start, date_end, type = row

            elif type != row[3]:
                # case of new type

                # inserting old row and creating new one
                processed_data.append((member_id, date_start, date_end, type))
                _, date_start, date_end, type = row

            elif datetime.datetime.strptime(row[1],'%Y-%m-%d')\
                 - datetime.datetime.strptime(date_end,'%Y-%m-%d')\
                     <= datetime.timedelta(3):
                # case of small time difference (<= 3 days) between old subscription and the new one
                # no row insertion but updating the end date of subscription
                date_end = row[2]
            else:
                # case of big difference (> 3 days) between old subscription and the new one
                # inserting old row and creating new one
                processed_data.append((member_id, date_start, date_end, type))
                _, date_start, date_end, type = row

        if not member_id == date_start == date_end == type == None:
            # finally inserting the last row if it exists
            processed_data.append((member_id, date_start, date_end, type))

        return processed_data

    def save_data(self, processed_data) -> None:
        """
        this method inserts data into a sqlite database table
            :params
            processed_data : python list of tuples returned by process_data
        """
        cur = self.connection.execute("""SELECT count(name) FROM sqlite_master WHERE type='table' AND name='subscriptions'""")
        if cur.fetchone()[0] == 0:
            # case of absence of table in data base
            # creating the table
            self.connection.execute("""CREATE TABLE subscriptions (member_id INTEGER, date_start TEXT, date_end TEXT, type INTEGER);""")

        # formating data for sql insertion
        str_values = str(processed_data)
        str_values = str_values[1:-1]
        str_values = str_values.replace('[','(')
        str_values = str_values.replace(']',')')
        
        # running sql insertion statement
        self.connection.execute(f"insert into subscriptions values {str_values};")
        self.connection.execute("commit")